import BuildSupport

# -----------------
# LOCAL ENVIRONMENT
# ----------------
Import('env')
lux_env = env.Clone()


# UIC Builder for compiling PyQt *.ui files.  Not sure why we
# explicitly need to pass in the PYTHONPATH here, but we do!
py_path = lux_env.get('PYTHONPATH', '')
sh_path = lux_env.get('PATH', '')
action_cmd = 'export PYTHONPATH=\'%s\' && export PATH=\'%s\' && pyuic4 $SOURCE -o $TARGET' % (py_path, sh_path)
uic_builder_py = Builder( action = action_cmd,
                          suffix = '.py',
                          src_suffix = '.ui',
                          single_source = True)

lux_env.Append( BUILDERS = { 'PyQtUic': uic_builder_py } )

# Sources
sources = Split("""panels/OutputPanel.ui
                   panels/PluginPanel.ui
                   panels/CalibrationPanel.ui""")
lux_env.PyQtUic(sources)
